name: ajuda
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #  functional
  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.2.19
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  connectivity_plus: ^3.0.4
  bot_toast: ^4.0.3
  google_maps_flutter: ^2.2.5
  location: ^4.4.0
  infinite_scroll_pagination: ^3.2.0
  rxdart: ^0.27.7
  flutter_svg: ^2.0.5
  http: ^0.13.5
  flutter_udid: ^2.0.1
  url_launcher: ^6.1.10
  easy_localization: ^3.0.1
  permission_handler: ^10.2.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  dropdown_button2: ^2.0.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  flutter_image_compress: ^1.1.3
  image_picker: ^0.8.7+4
  table_calendar: ^3.0.7
#  geocoder: ^0.2.1
  mask_text_input_formatter: ^2.4.0
  #ui
  webview_flutter: ^4.2.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  google_places_flutter: ^2.0.5
  google_places_for_flutter: ^1.0.1

  #firebase Pub
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  flutter_facebook_auth: ^5.0.8
  google_sign_in: ^6.1.0
  firebase_crashlytics: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/onBoarding/
    - assets/images/
    - assets/icon/
    - assets/translations/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  #  color: "#FE6D73"
  background_image: assets/splash.png
  fullscreen: true
  android_12:
    # image: assets/splash.png
    background_image: assets/splash.png
    fullscreen: true

  web: false